{% set name = "podofo" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5de607e15f192b8ad90738300759d88dea0f5ccdce3bf00048a0c932bc645154

build:
  number: 0
  ## should in principle work on mac and windows, just needs work to get it to build
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool  # [not win]
    - pkg-config  # [not win]
    - make  # [not win]
  host:
    - lua
    - openssl
    - fontconfig  # [unix]
    - freetype
    - libtiff
    - libpng
    - libidn11  # [unix]
    - zlib
    - libjpeg-turbo
  run:
    - lua
    - openssl
    - fontconfig  # [unix]
    - freetype
    - libidn11  # [unix]
    - libtiff
    - libpng
    - libjpeg-turbo
    - zlib
test:
  commands:
    - test -f ${PREFIX}/bin/podofobox  # [unix]

about:
  home: http://podofo.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: PoDoFo is a library to work with the PDF file format

extra:
  recipe-maintainers:
    - izahn
